config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  
  # establishes which view is for the root/home when we start our server and website
  root "home#index"
  get "home/about"
  
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  #associates the friends to user
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.expect(friend: [ :first_name, :last_name, :email, :phone, :twitter, :user_id ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # index html view in home folder
  def index
  end

  # about html view in home folder
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, html: {class:"bg-light p-3 rounded-3"}) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First name" %>
  </div>
  <div class="mb-3">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last name" %>
  </div>
  <div class="mb-3">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
  <div class="mb-3">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone number" %>
  </div>
  <div class="mb-3">
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>
  <div class="mb-3">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>
  <br>
  <div>
    <%= form.submit "Save", class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<tr id="<%= dom_id friend %>">
  <th scope="row"><%= friend.first_name %></th>
  <td><%= friend.last_name %></td>
  <td><%= friend.email %></td>
  <td><%= friend.phone %></td>
  <td><%= friend.twitter %></td>
  <td><%= friend.user_id %></td>
  <td><%= link_to "Show", friend %></td>
  <td><%= link_to "Edit", edit_friend_path(friend) %></td>
  <td><%= button_to "Destroy", friend, method: :delete, class:"btn btn-secondary btn-sm" %></td>
</tr>

app/views/friends/edit.html.erb
<% content_for :title, "Editing friend" %>
<h1>Editing friend</h1>
<br>
<%= render "form", friend: @friend %>
<br>
<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary btn-sm" %>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark btn-sm" %>
</div>

app/views/friends/index.html.erb
<% content_for :title, "Friends" %>
<div id="friends table-responsive">
  <table class="table table-hover table-striped">
    <thead class="table-dark">
      <tr>
        <th scope="col">First name:</th>
        <th scope="col">Last name:</th>
        <th scope="col">Email:</th>
        <th scope="col">Phone:</th>
        <th scope="col">Twitter:</th>
        <th scope="col">User Id:</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <!-- only shows user's friends -->
        <% if friend.user == current_user %>
          <%= render friend %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<% content_for :title, "New friend" %>
<h1>Add new friend</h1>
<br>
<%= render "form", friend: @friend %>
<br>
<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark btn-sm" %>
</div>

app/views/friends/show.html.erb
<div class="jumbotron bg-light p-5 rounded-3 ">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %> | 
    <%= @friend.phone %> | 
    <%= @friend.twitter %>
  </p>
  <hr class="my-4">
  <div>
    <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary btn-sm" %>
    <%= link_to "Back to friends", friends_path, class:"btn btn-secondary btn-dark btn-sm" %>
    <br/>
    <br/>
    <%= button_to "Destroy this friend", @friend, method: :delete, class:"btn btn-danger btn-sm" %>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-md bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "Friend App", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", friends_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add Friend", new_friend_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path(@user), method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search" data-bs-theme="light">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/home/index.html.erb
<h1>Hello World!</h1>
<p>This is my first Rails Webpage...</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= content_for(:title) || "Friends" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <!--telling rails to render this partial-->
    <%= render "home/header" %>
    <div class="container">
      <br>
      <% if notice %>
        <%= render "layouts/alerts"%>
      <% end%>
      <br>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
  </body>
</html>